import Script from "next/script";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       {/* ✅ Airwallex official script */}
       <Script
          src="https://checkout-demo.airwallex.com/assets/elements.bundle.min.js"
          strategy="beforeInteractive"
        />
        {children}
      </body>
    </html>
  );
}
